In [1]:
import pandas as pd

flood_df = pd.read_csv("data/flood_inventory.csv")

print(flood_df.shape)
print(flood_df.columns.tolist())

display(flood_df.head())

(6876, 23)
['Unnamed: 0', 'UEI', 'Start Date', 'End Date', 'Duration(Days)', 'Main Cause', 'Location', 'Districts', 'State', 'Latitude', 'Longitude', 'Severity', 'Area Affected', 'Human fatality', 'Human injured', 'Human Displaced', 'Animal Fatality', 'Description of Casualties/injured', 'Extent of damage ', 'Event Source', 'Event Souce ID', 'District_LGD_Codes', 'State_Codes']

,Unnamed: 0,UEI,Start Date,End Date,Duration(Days),Main Cause,Location,Districts,State,Latitude,...,Human fatality,Human injured,Human Displaced,Animal Fatality,Description of Casualties/injured,Extent of damage,Event Source,Event Souce ID,District_LGD_Codes,State_Codes
0,563,UEI-IMD-FL-1967-0001,02-07-1967 00:00,08-07-1967 00:00,7.0,flood,NaN,NaN,Assam,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,IMD,NaN,NaN,18
1,564,UEI-IMD-FL-1967-0002,22-07-1967 00:00,28-07-1967 00:00,7.0,flood,NaN,NaN,"Maharashtra, Gujarat",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,IMD,NaN,NaN,"27,24"
2,565,UEI-IMD-FL-1967-0003,01-08-1967 00:00,30-08-1967 00:00,30.0,flood,NaN,NaN,Uttar Pradesh,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,IMD,NaN,NaN,9
3,566,UEI-IMD-FL-1967-0004,08-09-1967 00:00,09-09-1967 00:00,2.0,flood,NaN,"Bhadrak, Dhenkanal, Jajapur, Subarnapur, Nuapa...","Odisha, Bihar, Uttar Pradesh, Madhya Pradesh, ...",NaN,...,NaN,NaN,NaN,NaN,NaN,Marooning of Barwer Express,IMD,NaN,"348, 352, 356, None, 368, 345, 349, 350, 359, ...","21,10,9,23,8,6"
4,567,UEI-IMD-FL-1968-0001,22-06-1968 00:00,28-06-1968 00:00,7.0,flood,NaN,NaN,Assam,NaN,...,NaN,NaN,NaN,NaN,NaN,"Affecting about one million people,an area of ...",IMD,NaN,NaN,18

In [9]:
rainfall_df = pd.read_csv("data/rainfall.csv", sep=";")

print(rainfall_df.shape)

(8790, 34)

In [2]:
flood_df["Start Date"] = pd.to_datetime(
    flood_df["Start Date"],
    dayfirst=True,
    errors="coerce"
)

flood_2022 = flood_df[
    flood_df["Start Date"].dt.year == 2022
].copy()

print("2022 flood events:", len(flood_2022))

display(
    flood_2022[
        ["Start Date", "State", "Districts",
         "Latitude", "Longitude", "Severity"]
    ].head(10)
)

2022 flood events: 1138

,Start Date,State,Districts,Latitude,Longitude,Severity
5085,2022-05-04,Andhra Pradesh,Guntur,NaN,NaN,NaN
5086,2022-05-04,Andhra Pradesh,several other district (Andhra Pradesh),NaN,NaN,NaN
5087,2022-07-18,Andhra Pradesh,West Godavari,NaN,NaN,NaN
5088,2022-07-18,Andhra Pradesh,Kurnool,NaN,NaN,NaN
5089,2022-07-18,Andhra Pradesh,West Godavari,NaN,NaN,NaN
5090,2022-07-01,Andhra Pradesh,Visakhapatnam,NaN,NaN,NaN
5091,2022-07-01,Andhra Pradesh,East Godavari,NaN,NaN,NaN
5092,2022-07-01,Andhra Pradesh,Dakshina Kannada,NaN,NaN,NaN
5093,2022-09-13,Andhra Pradesh,Srikakulam,NaN,NaN,NaN
5094,2022-04-06,Arunachal Pradesh,Itanagar,NaN,NaN,NaN

In [3]:
print("2022 flood records:", len(flood_2022))
print("District values:", flood_2022["Districts"].notna().sum())

2022 flood records: 1138
District values: 1136

In [4]:
print(
    flood_2022["Districts"]
    .dropna()
    .head(30)
    .to_list()
)

['Guntur', 'several other district (Andhra Pradesh)', 'West Godavari', 'Kurnool', 'West Godavari', 'Visakhapatnam', 'East Godavari', 'Dakshina Kannada', 'Srikakulam', 'Itanagar', 'Kurung Kumey', 'Anjaw', 'Upper Lower Subansiri, Anjaw, Changlang, Tawang, Papum Pare, Tirap, East Siang, Lohit, Kurung Kumey, Lower Lower Subansiri, East Kameng, West Kameng, West Kameng, West Kameng, Kra Daadi, Namsai, Longding, Upper Siang, Lower Siang, Dibang Valley, Lower Dibang Valley, Siang, Shi Yomi, Pakke Kessang, West Siang, Leparada, Kamle', 'Anjaw', 'Changlang', 'Itanagar', 'Kamle', 'Kurung Kumey', 'Lohit', 'Itanagar', 'Itanagar', 'Kurung Kumey', 'Itanagar', 'Tirap', 'Changlang', 'Anjaw', 'Kurung Kumey', 'Lower Dibang Valley', 'Itanagar', 'Upper Lower Subansiri']

In [5]:
# Clean state and district names
flood_2022["State"] = flood_2022["State"].str.strip()
flood_2022["Districts"] = flood_2022["Districts"].str.strip()

# Keep only rows with a specific district
flood_specific = flood_2022[
    flood_2022["Districts"].notna() &
    ~flood_2022["Districts"].str.contains(
        "several other|multiple|other district",
        case=False,
        na=False
    )
].copy()

print("Usable flood records:", len(flood_specific))

Usable flood records: 1135

In [6]:
print(flood_specific[["State", "Districts"]].head(30))

                  State                                          Districts
5085     Andhra Pradesh                                             Guntur
5087     Andhra Pradesh                                      West Godavari
5088     Andhra Pradesh                                            Kurnool
5089     Andhra Pradesh                                      West Godavari
5090     Andhra Pradesh                                      Visakhapatnam
5091     Andhra Pradesh                                      East Godavari
5092     Andhra Pradesh                                   Dakshina Kannada
5093     Andhra Pradesh                                         Srikakulam
5094  Arunachal Pradesh                                           Itanagar
5095  Arunachal Pradesh                                       Kurung Kumey
5096  Arunachal Pradesh                                              Anjaw
5097  Arunachal Pradesh  Upper Lower Subansiri, Anjaw, Changlang, Tawan...
5098  Arunachal Pradesh                                              Anjaw
5099  Arunachal Pradesh                                          Changlang
5100  Arunachal Pradesh                                           Itanagar
5101  Arunachal Pradesh                                              Kamle
5102  Arunachal Pradesh                                       Kurung Kumey
5103  Arunachal Pradesh                                              Lohit
5104  Arunachal Pradesh                                           Itanagar
5105  Arunachal Pradesh                                           Itanagar
5106  Arunachal Pradesh                                       Kurung Kumey
5107  Arunachal Pradesh                                           Itanagar
5108  Arunachal Pradesh                                              Tirap
5109  Arunachal Pradesh                                          Changlang
5110  Arunachal Pradesh                                              Anjaw
5111  Arunachal Pradesh                                       Kurung Kumey
5112  Arunachal Pradesh                                Lower Dibang Valley
5113  Arunachal Pradesh                                           Itanagar
5114  Arunachal Pradesh                              Upper Lower Subansiri
5115  Arunachal Pradesh                           West Kameng, West Kameng

In [7]:
# Keep only the first district when multiple districts are listed
flood_specific["District"] = (
    flood_specific["Districts"]
    .str.split(",")
    .str[0]
    .str.strip()
)

# Standardize text
flood_specific["State"] = flood_specific["State"].str.strip()
flood_specific["District"] = flood_specific["District"].str.strip()

print(flood_specific[["State", "District"]].head(20))

                  State               District
5085     Andhra Pradesh                 Guntur
5087     Andhra Pradesh          West Godavari
5088     Andhra Pradesh                Kurnool
5089     Andhra Pradesh          West Godavari
5090     Andhra Pradesh          Visakhapatnam
5091     Andhra Pradesh          East Godavari
5092     Andhra Pradesh       Dakshina Kannada
5093     Andhra Pradesh             Srikakulam
5094  Arunachal Pradesh               Itanagar
5095  Arunachal Pradesh           Kurung Kumey
5096  Arunachal Pradesh                  Anjaw
5097  Arunachal Pradesh  Upper Lower Subansiri
5098  Arunachal Pradesh                  Anjaw
5099  Arunachal Pradesh              Changlang
5100  Arunachal Pradesh               Itanagar
5101  Arunachal Pradesh                  Kamle
5102  Arunachal Pradesh           Kurung Kumey
5103  Arunachal Pradesh                  Lohit
5104  Arunachal Pradesh               Itanagar
5105  Arunachal Pradesh               Itanagar

In [8]:
print("Unique flood districts:", flood_specific["District"].nunique())
print("Unique states:", flood_specific["State"].nunique())

Unique flood districts: 354
Unique states: 27

In [10]:
rainfall_df["State"] = rainfall_df["state"].str.strip()
rainfall_df["District"] = rainfall_df["district"].str.strip()

In [11]:
rainfall_districts = set(
    rainfall_df["District"].str.lower()
)

flood_districts = set(
    flood_specific["District"].str.lower()
)

matched = rainfall_districts.intersection(flood_districts)

print("Rainfall districts:", len(rainfall_districts))
print("Flood districts:", len(flood_districts))
print("Matched districts:", len(matched))

Rainfall districts: 854
Flood districts: 354
Matched districts: 322

In [12]:
day_columns = [
    "1st", "2nd", "3rd", "4th", "5th", "6th", "7th",
    "8th", "9th", "10th", "11th", "12th", "13th", "14th",
    "15th", "16th", "17th", "18th", "19th", "20th", "21st",
    "22nd", "23rd", "24th", "25th", "26th", "27th", "28th",
    "29th", "30th", "31st"
]

rainfall_daily = rainfall_df.melt(
    id_vars=["State", "District", "month"],
    value_vars=day_columns,
    var_name="Day",
    value_name="Rainfall"
)

rainfall_daily["Day"] = (
    rainfall_daily["Day"]
    .str.extract(r"(\d+)")
    .astype(int)
)

print(rainfall_daily.shape)
display(rainfall_daily.head())

(272490, 5)

               State                  District  month  Day   Rainfall
0  Andaman & Nicobar                  Nicobars      1    1   0.000000
1  Andaman & Nicobar  North And Middle Andaman      1    1   0.000000
2  Andaman & Nicobar            South Andamans      1    1   0.000000
3     Andhra Pradesh                 Anantapur      1    1   0.379965
4     Andhra Pradesh                  Chittoor      1    1  14.144900

In [13]:
print(rainfall_daily.shape)
display(rainfall_daily.head())

(272490, 5)

               State                  District  month  Day   Rainfall
0  Andaman & Nicobar                  Nicobars      1    1   0.000000
1  Andaman & Nicobar  North And Middle Andaman      1    1   0.000000
2  Andaman & Nicobar            South Andamans      1    1   0.000000
3     Andhra Pradesh                 Anantapur      1    1   0.379965
4     Andhra Pradesh                  Chittoor      1    1  14.144900

In [14]:
rainfall_daily["Date"] = pd.to_datetime(
    "2022-" +
    rainfall_daily["month"].astype(str) + "-" +
    rainfall_daily["Day"].astype(str),
    errors="coerce"
)

print(rainfall_daily.shape)
display(rainfall_daily.head())

(272490, 6)

,State,District,month,Day,Rainfall,Date
0,Andaman & Nicobar,Nicobars,1,1,0.000000,2022-01-01
1,Andaman & Nicobar,North And Middle Andaman,1,1,0.000000,2022-01-01
2,Andaman & Nicobar,South Andamans,1,1,0.000000,2022-01-01
3,Andhra Pradesh,Anantapur,1,1,0.379965,2022-01-01
4,Andhra Pradesh,Chittoor,1,1,14.144900,2022-01-01

In [15]:
print(rainfall_daily["Date"].min())
print(rainfall_daily["Date"].max())

2022-01-01 00:00:00
2022-12-31 00:00:00

In [16]:
rainfall_daily = rainfall_daily.dropna(subset=["Date"]).copy()

print(rainfall_daily.shape)

(267364, 6)

In [17]:
flood_specific["Date"] = pd.to_datetime(
    flood_specific["Start Date"]
).dt.normalize()

In [18]:
rainfall_daily["State"] = rainfall_daily["State"].str.strip().str.lower()
rainfall_daily["District"] = rainfall_daily["District"].str.strip().str.lower()

flood_specific["State"] = flood_specific["State"].str.strip().str.lower()
flood_specific["District"] = flood_specific["District"].str.strip().str.lower()

In [19]:
flood_keys = flood_specific[
    ["State", "District", "Date"]
].drop_duplicates()

flood_keys["flood_occurred"] = 1

In [20]:
ml_data = rainfall_daily.merge(
    flood_keys,
    on=["State", "District", "Date"],
    how="left"
)

ml_data["flood_occurred"] = (
    ml_data["flood_occurred"]
    .fillna(0)
    .astype(int)
)

print(ml_data.shape)
print(ml_data["flood_occurred"].value_counts())

(267364, 7)
flood_occurred
0    266382
1       982
Name: count, dtype: int64

In [22]:
ml_data.to_csv("../data/processed/flood_rainfall_2022.csv", index=False)

OSError: Cannot save file into a non-existent directory: '..\data\processed'

In [23]:
print(ml_data.head())
print(ml_data.shape)

               State                  District  month  Day   Rainfall  \
0  andaman & nicobar                  nicobars      1    1   0.000000
1  andaman & nicobar  north and middle andaman      1    1   0.000000
2  andaman & nicobar            south andamans      1    1   0.000000
3     andhra pradesh                 anantapur      1    1   0.379965
4     andhra pradesh                  chittoor      1    1  14.144900

        Date  flood_occurred
0 2022-01-01               0
1 2022-01-01               0
2 2022-01-01               0
3 2022-01-01               0
4 2022-01-01               0
(267364, 7)

In [24]:
import os

os.makedirs("data/processed", exist_ok=True)

ml_data.to_csv(
    "data/processed/flood_rainfall_2022.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!

In [25]:
import os
print(os.path.exists("data/processed/flood_rainfall_2022.csv"))

True

Feature Engineering

In [26]:
ml_data = ml_data.sort_values(
    ["State", "District", "Date"]
).copy()

ml_data["rainfall_3day"] = (
    ml_data.groupby(["State", "District"])["Rainfall"]
    .transform(lambda x: x.rolling(3, min_periods=1).sum())
)

ml_data["rainfall_7day"] = (
    ml_data.groupby(["State", "District"])["Rainfall"]
    .transform(lambda x: x.rolling(7, min_periods=1).sum())
)

print(ml_data.shape)
display(ml_data.head())

(267364, 9)

,State,District,month,Day,Rainfall,Date,flood_occurred,rainfall_3day,rainfall_7day
6591,andaman & nicobar,nicobar,10,1,0.0,2022-10-01,0,0.0,0.0
15381,andaman & nicobar,nicobar,10,2,0.0,2022-10-02,0,0.0,0.0
24171,andaman & nicobar,nicobar,10,3,0.0,2022-10-03,0,0.0,0.0
32961,andaman & nicobar,nicobar,10,4,0.0,2022-10-04,0,0.0,0.0
41751,andaman & nicobar,nicobar,10,5,0.0,2022-10-05,0,0.0,0.0

In [27]:
ml_data.to_csv(
    "data/processed/flood_rainfall_features_2022.csv",
    index=False
)

print("Feature dataset saved successfully!")

Feature dataset saved successfully!

In [28]:
print(ml_data.shape)
print(ml_data["flood_occurred"].value_counts())

(267364, 9)
flood_occurred
0    266382
1       982
Name: count, dtype: int64