In [ ]:
import pandas as pd

flood_df = pd.read_csv("data/flood_inventory.csv")

print(flood_df.shape)
print(flood_df.columns.tolist())

display(flood_df.head())

(6876, 23)
['Unnamed: 0', 'UEI', 'Start Date', 'End Date', 'Duration(Days)', 'Main Cause', 'Location', 'Districts', 'State', 'Latitude', 'Longitude', 'Severity', 'Area Affected', 'Human fatality', 'Human injured', 'Human Displaced', 'Animal Fatality', 'Description of Casualties/injured', 'Extent of damage ', 'Event Source', 'Event Souce ID', 'District_LGD_Codes', 'State_Codes']

,Unnamed: 0,UEI,Start Date,End Date,Duration(Days),Main Cause,Location,Districts,State,Latitude,...,Human fatality,Human injured,Human Displaced,Animal Fatality,Description of Casualties/injured,Extent of damage,Event Source,Event Souce ID,District_LGD_Codes,State_Codes
0,563,UEI-IMD-FL-1967-0001,02-07-1967 00:00,08-07-1967 00:00,7.0,flood,NaN,NaN,Assam,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,IMD,NaN,NaN,18
1,564,UEI-IMD-FL-1967-0002,22-07-1967 00:00,28-07-1967 00:00,7.0,flood,NaN,NaN,"Maharashtra, Gujarat",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,IMD,NaN,NaN,"27,24"
2,565,UEI-IMD-FL-1967-0003,01-08-1967 00:00,30-08-1967 00:00,30.0,flood,NaN,NaN,Uttar Pradesh,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,IMD,NaN,NaN,9
3,566,UEI-IMD-FL-1967-0004,08-09-1967 00:00,09-09-1967 00:00,2.0,flood,NaN,"Bhadrak, Dhenkanal, Jajapur, Subarnapur, Nuapa...","Odisha, Bihar, Uttar Pradesh, Madhya Pradesh, ...",NaN,...,NaN,NaN,NaN,NaN,NaN,Marooning of Barwer Express,IMD,NaN,"348, 352, 356, None, 368, 345, 349, 350, 359, ...","21,10,9,23,8,6"
4,567,UEI-IMD-FL-1968-0001,22-06-1968 00:00,28-06-1968 00:00,7.0,flood,NaN,NaN,Assam,NaN,...,NaN,NaN,NaN,NaN,NaN,"Affecting about one million people,an area of ...",IMD,NaN,NaN,18

In [ ]:
rainfall_df = pd.read_csv("data/rainfall.csv", sep=";")

print(rainfall_df.shape)

(8790, 34)

In [ ]:
flood_df["Start Date"] = pd.to_datetime(
    flood_df["Start Date"],
    dayfirst=True,
    errors="coerce"
)

flood_2022 = flood_df[
    flood_df["Start Date"].dt.year == 2022
].copy()

print("2022 flood events:", len(flood_2022))

display(
    flood_2022[
        ["Start Date", "State", "Districts",
         "Latitude", "Longitude", "Severity"]
    ].head(10)
)

2022 flood events: 1138

,Start Date,State,Districts,Latitude,Longitude,Severity
5085,2022-05-04,Andhra Pradesh,Guntur,NaN,NaN,NaN
5086,2022-05-04,Andhra Pradesh,several other district (Andhra Pradesh),NaN,NaN,NaN
5087,2022-07-18,Andhra Pradesh,West Godavari,NaN,NaN,NaN
5088,2022-07-18,Andhra Pradesh,Kurnool,NaN,NaN,NaN
5089,2022-07-18,Andhra Pradesh,West Godavari,NaN,NaN,NaN
5090,2022-07-01,Andhra Pradesh,Visakhapatnam,NaN,NaN,NaN
5091,2022-07-01,Andhra Pradesh,East Godavari,NaN,NaN,NaN
5092,2022-07-01,Andhra Pradesh,Dakshina Kannada,NaN,NaN,NaN
5093,2022-09-13,Andhra Pradesh,Srikakulam,NaN,NaN,NaN
5094,2022-04-06,Arunachal Pradesh,Itanagar,NaN,NaN,NaN

In [ ]:
print("2022 flood records:", len(flood_2022))
print("District values:", flood_2022["Districts"].notna().sum())

2022 flood records: 1138
District values: 1136

In [ ]:
print(
    flood_2022["Districts"]
    .dropna()
    .head(30)
    .to_list()
)

['Guntur', 'several other district (Andhra Pradesh)', 'West Godavari', 'Kurnool', 'West Godavari', 'Visakhapatnam', 'East Godavari', 'Dakshina Kannada', 'Srikakulam', 'Itanagar', 'Kurung Kumey', 'Anjaw', 'Upper Lower Subansiri, Anjaw, Changlang, Tawang, Papum Pare, Tirap, East Siang, Lohit, Kurung Kumey, Lower Lower Subansiri, East Kameng, West Kameng, West Kameng, West Kameng, Kra Daadi, Namsai, Longding, Upper Siang, Lower Siang, Dibang Valley, Lower Dibang Valley, Siang, Shi Yomi, Pakke Kessang, West Siang, Leparada, Kamle', 'Anjaw', 'Changlang', 'Itanagar', 'Kamle', 'Kurung Kumey', 'Lohit', 'Itanagar', 'Itanagar', 'Kurung Kumey', 'Itanagar', 'Tirap', 'Changlang', 'Anjaw', 'Kurung Kumey', 'Lower Dibang Valley', 'Itanagar', 'Upper Lower Subansiri']

In [ ]:
# Clean state and district names
flood_2022["State"] = flood_2022["State"].str.strip()
flood_2022["Districts"] = flood_2022["Districts"].str.strip()

# Keep only rows with a specific district
flood_specific = flood_2022[
    flood_2022["Districts"].notna() &
    ~flood_2022["Districts"].str.contains(
        "several other|multiple|other district",
        case=False,
        na=False
    )
].copy()

print("Usable flood records:", len(flood_specific))

Usable flood records: 1135

In [ ]:
print(flood_specific[["State", "Districts"]].head(30))

                  State                                          Districts
5085     Andhra Pradesh                                             Guntur
5087     Andhra Pradesh                                      West Godavari
5088     Andhra Pradesh                                            Kurnool
5089     Andhra Pradesh                                      West Godavari
5090     Andhra Pradesh                                      Visakhapatnam
5091     Andhra Pradesh                                      East Godavari
5092     Andhra Pradesh                                   Dakshina Kannada
5093     Andhra Pradesh                                         Srikakulam
5094  Arunachal Pradesh                                           Itanagar
5095  Arunachal Pradesh                                       Kurung Kumey
5096  Arunachal Pradesh                                              Anjaw
5097  Arunachal Pradesh  Upper Lower Subansiri, Anjaw, Changlang, Tawan...
5098  Arunachal Pradesh                                              Anjaw
5099  Arunachal Pradesh                                          Changlang
5100  Arunachal Pradesh                                           Itanagar
5101  Arunachal Pradesh                                              Kamle
5102  Arunachal Pradesh                                       Kurung Kumey
5103  Arunachal Pradesh                                              Lohit
5104  Arunachal Pradesh                                           Itanagar
5105  Arunachal Pradesh                                           Itanagar
5106  Arunachal Pradesh                                       Kurung Kumey
5107  Arunachal Pradesh                                           Itanagar
5108  Arunachal Pradesh                                              Tirap
5109  Arunachal Pradesh                                          Changlang
5110  Arunachal Pradesh                                              Anjaw
5111  Arunachal Pradesh                                       Kurung Kumey
5112  Arunachal Pradesh                                Lower Dibang Valley
5113  Arunachal Pradesh                                           Itanagar
5114  Arunachal Pradesh                              Upper Lower Subansiri
5115  Arunachal Pradesh                           West Kameng, West Kameng

In [ ]:
# Keep only the first district when multiple districts are listed
flood_specific["District"] = (
    flood_specific["Districts"]
    .str.split(",")
    .str[0]
    .str.strip()
)

# Standardize text
flood_specific["State"] = flood_specific["State"].str.strip()
flood_specific["District"] = flood_specific["District"].str.strip()

print(flood_specific[["State", "District"]].head(20))

                  State               District
5085     Andhra Pradesh                 Guntur
5087     Andhra Pradesh          West Godavari
5088     Andhra Pradesh                Kurnool
5089     Andhra Pradesh          West Godavari
5090     Andhra Pradesh          Visakhapatnam
5091     Andhra Pradesh          East Godavari
5092     Andhra Pradesh       Dakshina Kannada
5093     Andhra Pradesh             Srikakulam
5094  Arunachal Pradesh               Itanagar
5095  Arunachal Pradesh           Kurung Kumey
5096  Arunachal Pradesh                  Anjaw
5097  Arunachal Pradesh  Upper Lower Subansiri
5098  Arunachal Pradesh                  Anjaw
5099  Arunachal Pradesh              Changlang
5100  Arunachal Pradesh               Itanagar
5101  Arunachal Pradesh                  Kamle
5102  Arunachal Pradesh           Kurung Kumey
5103  Arunachal Pradesh                  Lohit
5104  Arunachal Pradesh               Itanagar
5105  Arunachal Pradesh               Itanagar

In [ ]:
print("Unique flood districts:", flood_specific["District"].nunique())
print("Unique states:", flood_specific["State"].nunique())

Unique flood districts: 354
Unique states: 27

In [ ]:
rainfall_df["State"] = rainfall_df["state"].str.strip()
rainfall_df["District"] = rainfall_df["district"].str.strip()

In [ ]:
rainfall_districts = set(
    rainfall_df["District"].str.lower()
)

flood_districts = set(
    flood_specific["District"].str.lower()
)

matched = rainfall_districts.intersection(flood_districts)

print("Rainfall districts:", len(rainfall_districts))
print("Flood districts:", len(flood_districts))
print("Matched districts:", len(matched))

Rainfall districts: 854
Flood districts: 354
Matched districts: 322

In [ ]:
day_columns = [
    "1st", "2nd", "3rd", "4th", "5th", "6th", "7th",
    "8th", "9th", "10th", "11th", "12th", "13th", "14th",
    "15th", "16th", "17th", "18th", "19th", "20th", "21st",
    "22nd", "23rd", "24th", "25th", "26th", "27th", "28th",
    "29th", "30th", "31st"
]

rainfall_daily = rainfall_df.melt(
    id_vars=["State", "District", "month"],
    value_vars=day_columns,
    var_name="Day",
    value_name="Rainfall"
)

rainfall_daily["Day"] = (
    rainfall_daily["Day"]
    .str.extract(r"(\d+)")
    .astype(int)
)

print(rainfall_daily.shape)
display(rainfall_daily.head())

(272490, 5)

               State                  District  month  Day   Rainfall
0  Andaman & Nicobar                  Nicobars      1    1   0.000000
1  Andaman & Nicobar  North And Middle Andaman      1    1   0.000000
2  Andaman & Nicobar            South Andamans      1    1   0.000000
3     Andhra Pradesh                 Anantapur      1    1   0.379965
4     Andhra Pradesh                  Chittoor      1    1  14.144900

In [ ]:
print(rainfall_daily.shape)
display(rainfall_daily.head())

(272490, 5)

               State                  District  month  Day   Rainfall
0  Andaman & Nicobar                  Nicobars      1    1   0.000000
1  Andaman & Nicobar  North And Middle Andaman      1    1   0.000000
2  Andaman & Nicobar            South Andamans      1    1   0.000000
3     Andhra Pradesh                 Anantapur      1    1   0.379965
4     Andhra Pradesh                  Chittoor      1    1  14.144900

In [ ]:
rainfall_daily["Date"] = pd.to_datetime(
    "2022-" +
    rainfall_daily["month"].astype(str) + "-" +
    rainfall_daily["Day"].astype(str),
    errors="coerce"
)

print(rainfall_daily.shape)
display(rainfall_daily.head())

(272490, 6)

,State,District,month,Day,Rainfall,Date
0,Andaman & Nicobar,Nicobars,1,1,0.000000,2022-01-01
1,Andaman & Nicobar,North And Middle Andaman,1,1,0.000000,2022-01-01
2,Andaman & Nicobar,South Andamans,1,1,0.000000,2022-01-01
3,Andhra Pradesh,Anantapur,1,1,0.379965,2022-01-01
4,Andhra Pradesh,Chittoor,1,1,14.144900,2022-01-01

In [ ]:
print(rainfall_daily["Date"].min())
print(rainfall_daily["Date"].max())

2022-01-01 00:00:00
2022-12-31 00:00:00

In [ ]:
rainfall_daily = rainfall_daily.dropna(subset=["Date"]).copy()

print(rainfall_daily.shape)

(267364, 6)

In [ ]:
flood_specific["Date"] = pd.to_datetime(
    flood_specific["Start Date"]
).dt.normalize()

In [ ]:
rainfall_daily["State"] = rainfall_daily["State"].str.strip().str.lower()
rainfall_daily["District"] = rainfall_daily["District"].str.strip().str.lower()

flood_specific["State"] = flood_specific["State"].str.strip().str.lower()
flood_specific["District"] = flood_specific["District"].str.strip().str.lower()

In [ ]:
flood_keys = flood_specific[
    ["State", "District", "Date"]
].drop_duplicates()

flood_keys["flood_occurred"] = 1

In [ ]:
ml_data = rainfall_daily.merge(
    flood_keys,
    on=["State", "District", "Date"],
    how="left"
)

ml_data["flood_occurred"] = (
    ml_data["flood_occurred"]
    .fillna(0)
    .astype(int)
)

print(ml_data.shape)
print(ml_data["flood_occurred"].value_counts())

(267364, 7)
flood_occurred
0    266382
1       982
Name: count, dtype: int64

In [ ]:
ml_data.to_csv("../data/processed/flood_rainfall_2022.csv", index=False)

OSError: Cannot save file into a non-existent directory: '..\data\processed'

In [ ]:
print(ml_data.head())
print(ml_data.shape)

               State                  District  month  Day   Rainfall  \
0  andaman & nicobar                  nicobars      1    1   0.000000
1  andaman & nicobar  north and middle andaman      1    1   0.000000
2  andaman & nicobar            south andamans      1    1   0.000000
3     andhra pradesh                 anantapur      1    1   0.379965
4     andhra pradesh                  chittoor      1    1  14.144900

        Date  flood_occurred
0 2022-01-01               0
1 2022-01-01               0
2 2022-01-01               0
3 2022-01-01               0
4 2022-01-01               0
(267364, 7)

In [ ]:
import os

os.makedirs("data/processed", exist_ok=True)

ml_data.to_csv(
    "data/processed/flood_rainfall_2022.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!

In [ ]:
import os
print(os.path.exists("data/processed/flood_rainfall_2022.csv"))

True

Feature Engineering

In [ ]:
ml_data = ml_data.sort_values(
    ["State", "District", "Date"]
).copy()

ml_data["rainfall_3day"] = (
    ml_data.groupby(["State", "District"])["Rainfall"]
    .transform(lambda x: x.rolling(3, min_periods=1).sum())
)

ml_data["rainfall_7day"] = (
    ml_data.groupby(["State", "District"])["Rainfall"]
    .transform(lambda x: x.rolling(7, min_periods=1).sum())
)

print(ml_data.shape)
display(ml_data.head())

(267364, 9)

,State,District,month,Day,Rainfall,Date,flood_occurred,rainfall_3day,rainfall_7day
6591,andaman & nicobar,nicobar,10,1,0.0,2022-10-01,0,0.0,0.0
15381,andaman & nicobar,nicobar,10,2,0.0,2022-10-02,0,0.0,0.0
24171,andaman & nicobar,nicobar,10,3,0.0,2022-10-03,0,0.0,0.0
32961,andaman & nicobar,nicobar,10,4,0.0,2022-10-04,0,0.0,0.0
41751,andaman & nicobar,nicobar,10,5,0.0,2022-10-05,0,0.0,0.0

In [ ]:
ml_data.to_csv(
    "data/processed/flood_rainfall_features_2022.csv",
    index=False
)

print("Feature dataset saved successfully!")

Feature dataset saved successfully!

In [ ]:
print(ml_data.shape)
print(ml_data["flood_occurred"].value_counts())

(267364, 9)
flood_occurred
0    266382
1       982
Name: count, dtype: int64

new dataset

In [ ]:
import pandas as pd

flood_df = pd.read_csv("data/flood_inventory.csv")

print(flood_df.shape)
print(flood_df.columns.tolist())

(6876, 23)
['Unnamed: 0', 'UEI', 'Start Date', 'End Date', 'Duration(Days)', 'Main Cause', 'Location', 'Districts', 'State', 'Latitude', 'Longitude', 'Severity', 'Area Affected', 'Human fatality', 'Human injured', 'Human Displaced', 'Animal Fatality', 'Description of Casualties/injured', 'Extent of damage ', 'Event Source', 'Event Souce ID', 'District_LGD_Codes', 'State_Codes']

In [ ]:
flood_df["Start Date"] = pd.to_datetime(
    flood_df["Start Date"],
    dayfirst=True,
    errors="coerce"
)

print(flood_df["Start Date"].min())
print(flood_df["Start Date"].max())

1967-07-02 00:00:00
2023-09-12 00:00:00

In [ ]:
historical_10yr = flood_df[
    (flood_df["Start Date"].dt.year >= 2012) &
    (flood_df["Start Date"].dt.year <= 2021)
].copy()

print("2012–2021 flood records:", len(historical_10yr))

2012–2021 flood records: 1454

In [ ]:
print(
    "Districts available:",
    historical_10yr["Districts"].notna().sum()
)

print(
    "Districts missing:",
    historical_10yr["Districts"].isna().sum()
)

Districts available: 1450
Districts missing: 4

In [ ]:
print(
    historical_10yr[
        ["Start Date", "State", "Districts"]
    ].head(20)
)

     Start Date                      State  \
3631 2012-06-07  Andaman & Nicobar Islands
3632 2012-06-29  Andaman & Nicobar Islands
3633 2012-04-07             Andhra Pradesh
3634 2012-04-09             Andhra Pradesh
3635 2012-07-21             Andhra Pradesh
3636 2012-09-04             Andhra Pradesh
3637 2012-10-02             Andhra Pradesh
3638 2012-11-01             Andhra Pradesh
3639 2012-12-05             Andhra Pradesh
3640 2012-06-26          Arunachal Pradesh
3641 2012-09-15          Arunachal Pradesh
3642 2012-05-22                      Assam
3643 2012-06-04                      Assam
3644 2012-06-11                      Assam
3645 2012-06-22                      Assam
3646 2012-07-05                      Assam
3647 2012-07-10                      Assam
3648 2012-07-15                      Assam
3649 2012-07-29                      Assam
3650 2012-08-22                      Assam

                                              Districts
3631                           North And Middle Andaman
3632                           North And Middle Andaman
3633                            Kurnool, Medak,Prakasam
3634             Warangal, Warangal, Warangal, Warangal
3635                                          Hyderabad
3636                                  Krishna,Nizamabad
3637  East & West Godavari, East Godavari, West Goda...
3638  Chittoor, East Godavari, Guntur, Hyderabad, Kh...
3639                        Sri Potti Sriramulu Nellore
3640  Changlang, Dibang Valley, Lower Dibang Valley,...
3641  Most Upper Lower Subansiri, Anjaw, Changlang, ...
3642                                             Kamrup
3643                              Baksa, Jorhat,Nalbari
3644                              14 districts of Assam
3645  Tinsukia, Dhemaji, Dibrugarh, Lakhimpur, Sivas...
3646                                            Dhemaji
3647                                          Lakhimpur
3648                Bongaigaon, Barpeta, Dhemaji,Nagaon
3649                                          Lakhimpur
3650                Dhemaji, Kamrup, Lakhimpur,Sonitpur

In [ ]:
print("Districts available:", historical_10yr["Districts"].notna().sum())
print("Districts missing:", historical_10yr["Districts"].isna().sum())

Districts available: 1450
Districts missing: 4

In [ ]:
print(
    historical_10yr["Districts"]
    .dropna()
    .head(30)
    .tolist()
)

['North And Middle Andaman', 'North And Middle Andaman', 'Kurnool, Medak,Prakasam', 'Warangal, Warangal, Warangal, Warangal', 'Hyderabad', 'Krishna,Nizamabad', 'East & West Godavari, East Godavari, West Godavari, Guntur, Krishna,  Sri Potti Sriramulu Nellore, Prakasam, Palnadu, Guntur, Dakshina Kannada, West Godavari, Ntr,Kurnool, Krishna, Prakasam', 'Chittoor, East Godavari, Guntur, Hyderabad, Khammam, Krishna,  Sri Potti Sriramulu Nellore, Prakasam, Visakhapatnam,West Godavari', ' Sri Potti Sriramulu Nellore', 'Changlang, Dibang Valley, Lower Dibang Valley, Lohit, Upper Lower Subansiri', 'Most Upper Lower Subansiri, Anjaw, Changlang, Tawang, Papum Pare, Tirap, East Siang, Lohit, Kurung Kumey, Lower Lower Subansiri, East Kameng, West Kameng, West Kameng, West Kameng, Kra Daadi, Namsai, Longding, Upper Siang, Lower Siang, Dibang Valley, Lower Dibang Valley, Siang, Shi Yomi, Pak', 'Kamrup', 'Baksa, Jorhat,Nalbari', '14 districts of Assam', 'Tinsukia, Dhemaji, Dibrugarh, Lakhimpur, Sivasagar, Jorhat, Sonitpur, Golaghat, Udalguri, Chirang, Baksa, Nagaon, Kokrajhar, Darrang, Barpeta, Nalbari, Marigaon, Kamrup, Bongaigaon, Dhubri, Kamrup Metro, Goalpara, Dima Hasao, Karimganj, Hailakandi, Charaideo, Majuli, Biswanath, Hojai, South Salmara Mancachar, Karbi Anglong, West Karbi Anglong', 'Dhemaji', 'Lakhimpur', 'Bongaigaon, Barpeta, Dhemaji,Nagaon', 'Lakhimpur', 'Dhemaji, Kamrup, Lakhimpur,Sonitpur', 'Dhemaji', 'Tinsukia, Dhemaji, Dibrugarh, Lakhimpur, Sivasagar, Jorhat, Sonitpur, Golaghat, Udalguri, Chirang, Baksa, Nagaon, Kokrajhar, Darrang, Barpeta, Nalbari, Marigaon, Kamrup, Bongaigaon, Dhubri, Kamrup Metro, Goalpara, Dima Hasao, Cachar, Karimganj, Hailakandi, Charaideo, Majuli, Biswanath, Hojai, South Salmara Mancachar, Karbi Anglong, West Karbi Anglong', 'Patna', 'Patna', 'Raipur,neighborhood', 'Raipur', 'Uttar Kashi Bastar Kanker', 'Amreli, Bharuch,Dangs, Gir Somnath, Junagadh, Kachchh, Navsari, Tapi', 'Amreli, Bharuch,Dangs, Gir Somnath, Junagadh, Kachchh, Navsari, Tapi', 'Fatehabad,Panchkula']

In [ ]:
print("Districts available:", historical_10yr["Districts"].notna().sum())
print("Districts missing:", historical_10yr["Districts"].isna().sum())

Districts available: 1450
Districts missing: 4

In [ ]:
rainfall_df = pd.read_csv("data/rainfall.csv", sep=";")

rainfall_districts = set(
    rainfall_df["district"]
    .dropna()
    .str.strip()
    .str.lower()
    .unique()
)

print("Rainfall districts:", len(rainfall_districts))

Rainfall districts: 854

In [ ]:
print(rainfall_df.columns.tolist())
print(rainfall_df.shape)

['state', 'district', 'month', '1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th', '11th', '12th', '13th', '14th', '15th', '16th', '17th', '18th', '19th', '20th', '21st', '22nd', '23rd', '24th', '25th', '26th', '27th', '28th', '29th', '30th', '31st']
(8790, 34)

In [ ]:
rainfall_districts = set(
    rainfall_df["district"]
    .dropna()
    .str.strip()
    .str.lower()
    .unique()
)

print("Rainfall districts:", len(rainfall_districts))

Rainfall districts: 854

In [ ]:
rainfall_districts = set(
    rainfall_df["district"]
    .dropna()
    .astype(str)
    .str.strip()
    .str.lower()
    .unique()
)

print("Rainfall districts:", len(rainfall_districts))

Rainfall districts: 854

In [ ]:
def split_districts(value):
    if pd.isna(value):
        return []

    value = str(value).strip()

    # Ignore vague entries that don't identify districts
    if "districts of" in value.lower():
        return []

    districts = value.split(",")

    # Remove spaces and duplicate names within the same event
    districts = [
        d.strip()
        for d in districts
        if d.strip()
    ]

    return list(dict.fromkeys(districts))

In [ ]:
historical_10yr["district_list"] = (
    historical_10yr["Districts"]
    .apply(split_districts)
)

In [ ]:
print(
    historical_10yr[
        ["State", "Districts", "district_list"]
    ].head(20).to_string(index=False)
)

                    State                                                                                                                                                                                                                                                                                                                                                Districts                                                                                                                                                                                                                                                                                                                                              district_list
Andaman & Nicobar Islands                                                                                                                                                                                                                                                                                                                                 North And Middle Andaman                                                                                                                                                                                                                                                                                                                                 [North And Middle Andaman]
Andaman & Nicobar Islands                                                                                                                                                                                                                                                                                                                                 North And Middle Andaman                                                                                                                                                                                                                                                                                                                                 [North And Middle Andaman]
           Andhra Pradesh                                                                                                                                                                                                                                                                                                                                  Kurnool, Medak,Prakasam                                                                                                                                                                                                                                                                                                                                 [Kurnool, Medak, Prakasam]
           Andhra Pradesh                                                                                                                                                                                                                                                                                                                   Warangal, Warangal, Warangal, Warangal                                                                                                                                                                                                                                                                                                                                                 [Warangal]
           Andhra Pradesh                                                                                                                                                                                                                                                                                                                                                Hyderabad                                                                                                                                                                                                                                                                                                                                                [Hyderabad]
           Andhra Pradesh                                                                                                                                                                                                                                                                                                                                        Krishna,Nizamabad                                                                                                                                                                                                                                                                                                                                       [Krishna, Nizamabad]
           Andhra Pradesh                                                                                                                                                            East & West Godavari, East Godavari, West Godavari, Guntur, Krishna,  Sri Potti Sriramulu Nellore, Prakasam, Palnadu, Guntur, Dakshina Kannada, West Godavari, Ntr,Kurnool, Krishna, Prakasam                                                                                                                                                                                                      [East & West Godavari, East Godavari, West Godavari, Guntur, Krishna, Sri Potti Sriramulu Nellore, Prakasam, Palnadu, Dakshina Kannada, Ntr, Kurnool]
           Andhra Pradesh                                                                                                                                                                                                                        Chittoor, East Godavari, Guntur, Hyderabad, Khammam, Krishna,  Sri Potti Sriramulu Nellore, Prakasam, Visakhapatnam,West Godavari                                                                                                                                                                                                                        [Chittoor, East Godavari, Guntur, Hyderabad, Khammam, Krishna, Sri Potti Sriramulu Nellore, Prakasam, Visakhapatnam, West Godavari]
           Andhra Pradesh                                                                                                                                                                                                                                                                                                                              Sri Potti Sriramulu Nellore                                                                                                                                                                                                                                                                                                                              [Sri Potti Sriramulu Nellore]
        Arunachal Pradesh                                                                                                                                                                                                                                                                              Changlang, Dibang Valley, Lower Dibang Valley, Lohit, Upper Lower Subansiri                                                                                                                                                                                                                                                                              [Changlang, Dibang Valley, Lower Dibang Valley, Lohit, Upper Lower Subansiri]
        Arunachal Pradesh                                                     Most Upper Lower Subansiri, Anjaw, Changlang, Tawang, Papum Pare, Tirap, East Siang, Lohit, Kurung Kumey, Lower Lower Subansiri, East Kameng, West Kameng, West Kameng, West Kameng, Kra Daadi, Namsai, Longding, Upper Siang, Lower Siang, Dibang Valley, Lower Dibang Valley, Siang, Shi Yomi, Pak                                                                               [Most Upper Lower Subansiri, Anjaw, Changlang, Tawang, Papum Pare, Tirap, East Siang, Lohit, Kurung Kumey, Lower Lower Subansiri, East Kameng, West Kameng, Kra Daadi, Namsai, Longding, Upper Siang, Lower Siang, Dibang Valley, Lower Dibang Valley, Siang, Shi Yomi, Pak]
                    Assam                                                                                                                                                                                                                                                                                                                                                   Kamrup                                                                                                                                                                                                                                                                                                                                                   [Kamrup]
                    Assam                                                                                                                                                                                                                                                                                                                                    Baksa, Jorhat,Nalbari                                                                                                                                                                                                                                                                                                                                   [Baksa, Jorhat, Nalbari]
                    Assam                                                                                                                                                                                                                                                                                                                                    14 districts of Assam                                                                                                                                                                                                                                                                                                                                                         []
                    Assam Tinsukia, Dhemaji, Dibrugarh, Lakhimpur, Sivasagar, Jorhat, Sonitpur, Golaghat, Udalguri, Chirang, Baksa, Nagaon, Kokrajhar, Darrang, Barpeta, Nalbari, Marigaon, Kamrup, Bongaigaon, Dhubri, Kamrup Metro, Goalpara, Dima Hasao, Karimganj, Hailakandi, Charaideo, Majuli, Biswanath, Hojai, South Salmara Mancachar, Karbi Anglong, West Karbi Anglong [Tinsukia, Dhemaji, Dibrugarh, Lakhimpur, Sivasagar, Jorhat, Sonitpur, Golaghat, Udalguri, Chirang, Baksa, Nagaon, Kokrajhar, Darrang, Barpeta, Nalbari, Marigaon, Kamrup, Bongaigaon, Dhubri, Kamrup Metro, Goalpara, Dima Hasao, Karimganj, Hailakandi, Charaideo, Majuli, Biswanath, Hojai, South Salmara Mancachar, Karbi Anglong, West Karbi Anglong]
                    Assam                                                                                                                                                                                                                                                                                                                                                  Dhemaji                                                                                                                                                                                                                                                                                                                                                  [Dhemaji]
                    Assam                                                                                                                                                                                                                                                                                                                                                Lakhimpur                                                                                                                                                                                                                                                                                                                                                [Lakhimpur]
                    Assam                                                                                                                                                                                                                                                                                                                      Bongaigaon, Barpeta, Dhemaji,Nagaon                                                                                                                                                                                                                                                                                                                     [Bongaigaon, Barpeta, Dhemaji, Nagaon]
                    Assam                                                                                                                                                                                                                                                                                                                                                Lakhimpur                                                                                                                                                                                                                                                                                                                                                [Lakhimpur]
                    Assam                                                                                                                                                                                                                                                                                                                      Dhemaji, Kamrup, Lakhimpur,Sonitpur                                                                                                                                                                                                                                                                                                                     [Dhemaji, Kamrup, Lakhimpur, Sonitpur]

In [ ]:
total_district_entries = historical_10yr["district_list"].apply(len).sum()

print("Total district-event entries:", total_district_entries)

Total district-event entries: 5274

In [ ]:
flood_districts = historical_10yr.explode(
    "district_list"
).copy()

flood_districts = flood_districts[
    flood_districts["district_list"].notna() &
    (flood_districts["district_list"] != "")
].copy()

print("District-event rows:", len(flood_districts))

District-event rows: 5274

In [ ]:
flood_districts["district_clean"] = (
    flood_districts["district_list"]
    .astype(str)
    .str.strip()
    .str.lower()
)

print(
    flood_districts[
        ["State", "district_list", "district_clean"]
    ].head(20).to_string(index=False)
)

                    State               district_list              district_clean
Andaman & Nicobar Islands    North And Middle Andaman    north and middle andaman
Andaman & Nicobar Islands    North And Middle Andaman    north and middle andaman
           Andhra Pradesh                     Kurnool                     kurnool
           Andhra Pradesh                       Medak                       medak
           Andhra Pradesh                    Prakasam                    prakasam
           Andhra Pradesh                    Warangal                    warangal
           Andhra Pradesh                   Hyderabad                   hyderabad
           Andhra Pradesh                     Krishna                     krishna
           Andhra Pradesh                   Nizamabad                   nizamabad
           Andhra Pradesh        East & West Godavari        east & west godavari
           Andhra Pradesh               East Godavari               east godavari
           Andhra Pradesh               West Godavari               west godavari
           Andhra Pradesh                      Guntur                      guntur
           Andhra Pradesh                     Krishna                     krishna
           Andhra Pradesh Sri Potti Sriramulu Nellore sri potti sriramulu nellore
           Andhra Pradesh                    Prakasam                    prakasam
           Andhra Pradesh                     Palnadu                     palnadu
           Andhra Pradesh            Dakshina Kannada            dakshina kannada
           Andhra Pradesh                         Ntr                         ntr
           Andhra Pradesh                     Kurnool                     kurnool

In [ ]:
matched_districts = (
    flood_districts["district_clean"]
    .isin(rainfall_districts)
)

print("Matched district-event rows:", matched_districts.sum())
print("Unmatched district-event rows:", (~matched_districts).sum())

Matched district-event rows: 4866
Unmatched district-event rows: 408

In [ ]:
unmatched = flood_districts[
    ~flood_districts["district_clean"].isin(rainfall_districts)
].copy()

print("Unique unmatched districts:", unmatched["district_clean"].nunique())

print(
    unmatched["district_clean"]
    .value_counts()
    .head(50)
)

Unique unmatched districts: 106
district_clean
mumbai                              28
uttar kashia kannada                26
bara banki                          24
dharashiv                           19
warangal                            13
beedar                              12
kanpur nagar dehat                  11
visakhapatnam                       10
ahmedabad                            9
devbhumi dwarka dwarka               9
namchi                               8
uttar kashi kashi                    8
thoothukkudi                         8
kanpur nagar nagar                   8
viluppuram                           7
sant kabir nagar                     7
mancachar                            7
sri potti sriramulu nellore          6
ghazipurr                            6
gyalshing                            6
gangtok                              6
chamarajanagaraa chikkaballapura     6
bagalkotee                           6
upper lower subansiri                5
kanniyakumariumari                   5
sshrawasti                           5
ferozepur                            5
sri sri muktsar sahib sahib          5
lahul and spiti                      5
garhwal                              5
mangan                               4
khargone (khargone (west nimar))     4
ananthapuramuamu                     4
cooch behar                          4
mahrajganj                           4
north 24 parganas                    4
s.a.s nagar*                         4
lower lower subansiri                3
pak                                  3
narmadapuram                         3
bagalkotee belagavi                  3
south 24 parganas                    3
bagalkotee bengaluru urban           3
purba purba bardhaman                3
north westduar                       3
east & west godavari                 2
uttar kashi bastar kanker            2
parts of uttar kashiakhand           2
parts of meghalaya                   2
parts of sikkim                      2
Name: count, dtype: int64

In [ ]:
check_names = [
    "mumbai",
    "dharashiv",
    "warangal",
    "beedar",
    "visakhapatnam",
    "ahmedabad",
    "namchi",
    "thoothukkudi",
    "viluppuram",
    "sri potti sriramulu nellore"
]

for name in check_names:
    matches = [
        d for d in rainfall_districts
        if name in d or d in name
    ]
    
    print(f"\n{name}:")
    print(matches[:20])

mumbai:
['sub urban mumbai', 'mumbai suburban', 'mumbai city']

dharashiv:
['dhar']

warangal:
['warangal (rural)', 'warangal (urban)', 'warangal urban', 'warangal rural']

beedar:
['beed']

visakhapatnam:
['patna']

ahmedabad:
[]

namchi:
[]

thoothukkudi:
[]

viluppuram:
[]

sri potti sriramulu nellore:
['potti sriramulu nellore']

In [ ]:
rainfall_keys = set(
    rainfall_df.apply(
        lambda row: (
            str(row["state"]).strip().lower(),
            str(row["district"]).strip().lower()
        ),
        axis=1
    )
)

print("State-District combinations:", len(rainfall_keys))

State-District combinations: 863

In [ ]:
flood_districts["state_clean"] = (
    flood_districts["State"]
    .astype(str)
    .str.strip()
    .str.lower()
)

flood_districts["state_district_key"] = list(
    zip(
        flood_districts["state_clean"],
        flood_districts["district_clean"]
    )
)

In [ ]:
matched = flood_districts["state_district_key"].isin(rainfall_keys)

print("Matched:", matched.sum())
print("Unmatched:", (~matched).sum())

Matched: 4739
Unmatched: 535

In [ ]:
clean_flood_districts = flood_districts[
    flood_districts["state_district_key"].isin(rainfall_keys)
].copy()

print(clean_flood_districts.shape)

(4739, 27)

In [ ]:
historical_flood_count = (
    clean_flood_districts
    .groupby(["state_clean", "district_clean"])["UEI"]
    .nunique()
    .reset_index()
)

historical_flood_count = historical_flood_count.rename(
    columns={
        "state_clean": "state",
        "district_clean": "district",
        "UEI": "historical_flood_count_10yr"
    }
)

print(historical_flood_count.head(20))
print("Districts with historical flood data:",
      len(historical_flood_count))

                state             district  historical_flood_count_10yr
0      andhra pradesh             chittoor                            4
1      andhra pradesh        east godavari                           11
2      andhra pradesh               guntur                            7
3      andhra pradesh              krishna                            9
4      andhra pradesh              kurnool                            7
5      andhra pradesh             prakasam                            7
6      andhra pradesh           srikakulam                            4
7      andhra pradesh         vizianagaram                            3
8      andhra pradesh        west godavari                           14
9      andhra pradesh               y.s.r.                            6
10  arunachal pradesh                anjaw                            3
11  arunachal pradesh            changlang                            6
12  arunachal pradesh        dibang valley                            6
13  arunachal pradesh          east kameng                            3
14  arunachal pradesh           east siang                            4
15  arunachal pradesh            kra daadi                            3
16  arunachal pradesh         kurung kumey                            3
17  arunachal pradesh                lohit                            6
18  arunachal pradesh             longding                            3
19  arunachal pradesh  lower dibang valley                            5
Districts with historical flood data: 554

In [ ]:
ml_data = pd.read_csv(
    "data/processed/flood_rainfall_features_2022.csv"
)

print(ml_data.shape)
print(ml_data.columns.tolist())
print(ml_data.head())

(267364, 9)
['State', 'District', 'month', 'Day', 'Rainfall', 'Date', 'flood_occurred', 'rainfall_3day', 'rainfall_7day']
               State District  month  Day  Rainfall        Date  \
0  andaman & nicobar  nicobar     10    1       0.0  2022-10-01
1  andaman & nicobar  nicobar     10    2       0.0  2022-10-02
2  andaman & nicobar  nicobar     10    3       0.0  2022-10-03
3  andaman & nicobar  nicobar     10    4       0.0  2022-10-04
4  andaman & nicobar  nicobar     10    5       0.0  2022-10-05

   flood_occurred  rainfall_3day  rainfall_7day
0               0            0.0            0.0
1               0            0.0            0.0
2               0            0.0            0.0
3               0            0.0            0.0
4               0            0.0            0.0

In [ ]:
print(historical_flood_count.head())
print(historical_flood_count.shape)

            state       district  historical_flood_count_10yr
0  andhra pradesh       chittoor                            4
1  andhra pradesh  east godavari                           11
2  andhra pradesh         guntur                            7
3  andhra pradesh        krishna                            9
4  andhra pradesh        kurnool                            7
(554, 3)

In [ ]:
ml_data["state"] = (
    ml_data["State"]
    .astype(str)
    .str.strip()
    .str.lower()
)

ml_data["district"] = (
    ml_data["District"]
    .astype(str)
    .str.strip()
    .str.lower()
)

In [ ]:
ml_data = ml_data.merge(
    historical_flood_count,
    on=["state", "district"],
    how="left"
)

In [ ]:
print(ml_data.shape)

print(
    "Rows with historical flood data:",
    ml_data["historical_flood_count_10yr"].notna().sum()
)

print(
    "Rows without historical flood data:",
    ml_data["historical_flood_count_10yr"].isna().sum()
)

(267364, 12)
Rows with historical flood data: 197308
Rows without historical flood data: 70056

In [ ]:
print(historical_flood_count.head())

            state       district  historical_flood_count_10yr
0  andhra pradesh       chittoor                            4
1  andhra pradesh  east godavari                           11
2  andhra pradesh         guntur                            7
3  andhra pradesh        krishna                            9
4  andhra pradesh        kurnool                            7

In [ ]:
ml_data["state"] = (
    ml_data["State"]
    .astype(str)
    .str.strip()
    .str.lower()
)

ml_data["district"] = (
    ml_data["District"]
    .astype(str)
    .str.strip()
    .str.lower()
)

In [ ]:
ml_data = ml_data.merge(
    historical_flood_count,
    on=["state", "district"],
    how="left"
)

In [ ]:
print(
    ml_data[
        [
            "historical_flood_count_10yr_x",
            "historical_flood_count_10yr_y"
        ]
    ].head(20)
)

    historical_flood_count_10yr_x  historical_flood_count_10yr_y
0                             NaN                            NaN
1                             NaN                            NaN
2                             NaN                            NaN
3                             NaN                            NaN
4                             NaN                            NaN
5                             NaN                            NaN
6                             NaN                            NaN
7                             NaN                            NaN
8                             NaN                            NaN
9                             NaN                            NaN
10                            NaN                            NaN
11                            NaN                            NaN
12                            NaN                            NaN
13                            NaN                            NaN
14                            NaN                            NaN
15                            NaN                            NaN
16                            NaN                            NaN
17                            NaN                            NaN
18                            NaN                            NaN
19                            NaN                            NaN

In [ ]:
print(ml_data.columns.tolist())

['State', 'District', 'month', 'Day', 'Rainfall', 'Date', 'flood_occurred', 'rainfall_3day', 'rainfall_7day', 'state', 'district', 'historical_flood_count_10yr_x', 'historical_flood_count_10yr_y']

In [ ]:
ml_data = ml_data.drop(
    columns=[
        "historical_flood_count_10yr_x",
        "historical_flood_count_10yr_y"
    ]
)

In [ ]:
print(
    ml_data[
        (ml_data["state"] == "andhra pradesh") &
        (ml_data["district"] == "chittoor")
    ][["State", "District", "state", "district"]].head()
)

               State  District           state  district
1460  andhra pradesh  chittoor  andhra pradesh  chittoor
1461  andhra pradesh  chittoor  andhra pradesh  chittoor
1462  andhra pradesh  chittoor  andhra pradesh  chittoor
1463  andhra pradesh  chittoor  andhra pradesh  chittoor
1464  andhra pradesh  chittoor  andhra pradesh  chittoor

In [ ]:
print(
    historical_flood_count[
        (historical_flood_count["state"] == "andhra pradesh") &
        (historical_flood_count["district"] == "chittoor")
    ]
)

            state  district  historical_flood_count_10yr
0  andhra pradesh  chittoor                            4

In [ ]:
ml_data = ml_data.drop(
    columns=[
        "historical_flood_count_10yr_x",
        "historical_flood_count_10yr_y"
    ],
    errors="ignore"
)

In [ ]:
ml_data["state"] = (
    ml_data["State"]
    .astype(str)
    .str.strip()
    .str.lower()
)

ml_data["district"] = (
    ml_data["District"]
    .astype(str)
    .str.strip()
    .str.lower()
)

historical_flood_count["state"] = (
    historical_flood_count["state"]
    .astype(str)
    .str.strip()
    .str.lower()
)

historical_flood_count["district"] = (
    historical_flood_count["district"]
    .astype(str)
    .str.strip()
    .str.lower()
)

In [ ]:
test_merge = ml_data.merge(
    historical_flood_count,
    on=["state", "district"],
    how="left"
)

print(
    test_merge[
        (test_merge["state"] == "andhra pradesh") &
        (test_merge["district"] == "chittoor")
    ][
        ["State", "District", "historical_flood_count_10yr"]
    ].head()
)

               State  District  historical_flood_count_10yr
1460  andhra pradesh  chittoor                          4.0
1461  andhra pradesh  chittoor                          4.0
1462  andhra pradesh  chittoor                          4.0
1463  andhra pradesh  chittoor                          4.0
1464  andhra pradesh  chittoor                          4.0

In [ ]:
print(
    "Rows with historical flood data:",
    test_merge["historical_flood_count_10yr"].notna().sum()
)

print(
    "Rows without historical flood data:",
    test_merge["historical_flood_count_10yr"].isna().sum()
)

Rows with historical flood data: 197308
Rows without historical flood data: 70056

In [ ]:
print(
    test_merge[
        [
            "State",
            "District",
            "Date",
            "Rainfall",
            "rainfall_3day",
            "rainfall_7day",
            "historical_flood_count_10yr",
            "flood_occurred"
        ]
    ].head(20)
)

                State District        Date  Rainfall  rainfall_3day  \
0   andaman & nicobar  nicobar  2022-10-01       0.0            0.0
1   andaman & nicobar  nicobar  2022-10-02       0.0            0.0
2   andaman & nicobar  nicobar  2022-10-03       0.0            0.0
3   andaman & nicobar  nicobar  2022-10-04       0.0            0.0
4   andaman & nicobar  nicobar  2022-10-05       0.0            0.0
5   andaman & nicobar  nicobar  2022-10-06       0.0            0.0
6   andaman & nicobar  nicobar  2022-10-07       0.0            0.0
7   andaman & nicobar  nicobar  2022-10-08       0.0            0.0
8   andaman & nicobar  nicobar  2022-10-09       0.0            0.0
9   andaman & nicobar  nicobar  2022-10-10       0.0            0.0
10  andaman & nicobar  nicobar  2022-10-11       0.0            0.0
11  andaman & nicobar  nicobar  2022-10-12       0.0            0.0
12  andaman & nicobar  nicobar  2022-10-13       0.0            0.0
13  andaman & nicobar  nicobar  2022-10-14       0.0            0.0
14  andaman & nicobar  nicobar  2022-10-15       0.0            0.0
15  andaman & nicobar  nicobar  2022-10-16       0.0            0.0
16  andaman & nicobar  nicobar  2022-10-17       0.0            0.0
17  andaman & nicobar  nicobar  2022-10-18       0.0            0.0
18  andaman & nicobar  nicobar  2022-10-19       0.0            0.0
19  andaman & nicobar  nicobar  2022-10-20       0.0            0.0

    rainfall_7day  historical_flood_count_10yr  flood_occurred
0             0.0                          NaN               0
1             0.0                          NaN               0
2             0.0                          NaN               0
3             0.0                          NaN               0
4             0.0                          NaN               0
5             0.0                          NaN               0
6             0.0                          NaN               0
7             0.0                          NaN               0
8             0.0                          NaN               0
9             0.0                          NaN               0
10            0.0                          NaN               0
11            0.0                          NaN               0
12            0.0                          NaN               0
13            0.0                          NaN               0
14            0.0                          NaN               0
15            0.0                          NaN               0
16            0.0                          NaN               0
17            0.0                          NaN               0
18            0.0                          NaN               0
19            0.0                          NaN               0

In [ ]:
print(test_merge["historical_flood_count_10yr"].describe())

count    197308.000000
mean          8.638727
std          10.096470
min           1.000000
25%           3.000000
50%           5.000000
75%          10.000000
max         107.000000
Name: historical_flood_count_10yr, dtype: float64

In [ ]:
ml_data = test_merge.copy()

ml_data = ml_data.drop(
    columns=["state", "district"],
    errors="ignore"
)

ml_data.to_csv(
    "data/processed/flood_rainfall_features_2022.csv",
    index=False
)

print("Saved successfully!")
print(ml_data.shape)
print(ml_data.columns.tolist())

Saved successfully!
(267364, 10)
['State', 'District', 'month', 'Day', 'Rainfall', 'Date', 'flood_occurred', 'rainfall_3day', 'rainfall_7day', 'historical_flood_count_10yr']

date:16-aug